# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pN7qhC9_2GBakMdqB1hgEIC9nZkKTeWV

## Step 1: Import Libraries
"""

import tensorflow as tf
import zipfile
from google.colab import files
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.applications import MobileNetV2

"""## Step 2: Set Up Kaggle API Token"""

import os

os.makedirs('/root/.kaggle', exist_ok=True)

with open('/root/.kaggle/access_token', 'w') as f:
    f.write('KGAT_398ee2c21c92e2ed6268cd2e01b125ee')

!chmod 600 /root/.kaggle/access_token
!pip install kaggle -q

"""## Step 3: Download the Dataset Directly into Colab"""

!kaggle datasets download -d sriramr/fruits-fresh-and-rotten-for-classification -p /content --unzip

"""## Step 4: Check the Downloaded Folders"""

import os
print(os.listdir('/content'))

"""## Step 5: Explore the Dataset Folder Structure"""

import os
print(os.listdir('/content/dataset'))

"""## Step 6: Check Inside train, test, and nested dataset Folders"""

import os

print("Inside train:", os.listdir('/content/dataset/train'))
print("Inside test:", os.listdir('/content/dataset/test'))
print("Inside nested dataset:", os.listdir('/content/dataset/dataset'))

"""## Step 7: Load the Data (6-Class Classification)
Since we have 6 categories (fresh/rotten × apple/banana/orange), we use `class_mode='categorical'` instead of `binary`.
"""

IMG_SIZE = (128, 128)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_data = train_datagen.flow_from_directory(
    '/content/dataset/train',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_data = train_datagen.flow_from_directory(
    '/content/dataset/train',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

print(train_data.class_indices)

"""## Step 8: Custom CNN Model (Built From Scratch, 6 Classes)
Three Conv2D + MaxPooling layers extract features from the images (edges, colors, texture). `Flatten` converts those features into a single line, then `Dense` layers make the decision. The final layer has 6 units with `softmax` activation, giving a probability for each of the 6 classes.
"""

custom_cnn = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(6, activation='softmax')
])

"""## Step 9: Compile the Custom CNN
`categorical_crossentropy` is the loss function used for multi-class problems (more than 2 classes).
"""

custom_cnn.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

custom_cnn.summary()

"""## Step 10: Load Pretrained MobileNetV2 (Transfer Learning)
`MobileNetV2` is already trained on millions of images (ImageNet dataset). `include_top=False` means we're not using its original final layers — we'll add our own. `trainable = False` freezes the pretrained part so it won't be retrained.
"""

base_model = MobileNetV2(
    input_shape=(128,128,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

"""## Step 11: Add Custom Layers on Top (6 Classes)"""

transfer_model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(6, activation='softmax')
])

"""## Step 12: Compile the Transfer Learning Model"""

transfer_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

transfer_model.summary()

"""## Step 13: Train the Custom CNN
Both models are trained on the same training/validation data so their results can be directly compared.
"""

history_cnn = custom_cnn.fit(train_data, validation_data=val_data, epochs=10)

"""## Step 14: Train the Transfer Learning Model"""

history_transfer = transfer_model.fit(train_data, validation_data=val_data, epochs=10)

"""## Step 15: Plot Accuracy and Loss Comparison
This compares how both models performed during training — validation accuracy and validation loss, side by side.
"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Accuracy comparison
axes[0].plot(history_cnn.history['val_accuracy'], label='Custom CNN')
axes[0].plot(history_transfer.history['val_accuracy'], label='Transfer Learning (MobileNetV2)')
axes[0].set_title('Validation Accuracy Comparison')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy')
axes[0].legend()

# Loss comparison
axes[1].plot(history_cnn.history['val_loss'], label='Custom CNN')
axes[1].plot(history_transfer.history['val_loss'], label='Transfer Learning (MobileNetV2)')
axes[1].set_title('Validation Loss Comparison')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()

plt.tight_layout()
plt.show()

"""## Step 16: Evaluate Both Models on Test Data
This checks performance on completely unseen images (the `test` folder we saw earlier).
"""

test_datagen = ImageDataGenerator(rescale=1./255)

test_data = test_datagen.flow_from_directory(
    '/content/dataset/test',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

cnn_test_loss, cnn_test_acc = custom_cnn.evaluate(test_data)
print(f"Custom CNN Test Accuracy: {cnn_test_acc*100:.2f}%")

transfer_test_loss, transfer_test_acc = transfer_model.evaluate(test_data)
print(f"Transfer Learning Test Accuracy: {transfer_test_acc*100:.2f}%")

"""## Step 17: Save Both Models
Saving the trained models so we don't need to retrain them every time — we'll load these directly in the Gradio app.
"""

custom_cnn.save('/content/custom_cnn_model.h5')
transfer_model.save('/content/transfer_model.h5')

print("Models saved successfully")

from google.colab import files

files.download('/content/custom_cnn_model.h5')
files.download('/content/transfer_model.h5')

"""## Step 18: Install Gradio (if not already installed)"""

!pip install gradio -q

"""## Step 19: Build the Prediction Function
This function takes an uploaded image, resizes it, and returns predictions from both models.
"""

import numpy as np
from tensorflow.keras.preprocessing import image

# Class names in the same order as train_data.class_indices
class_names = list(train_data.class_indices.keys())

def predict_fruit(img):
    img = img.resize((128, 128))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    cnn_pred = custom_cnn.predict(img_array)[0]
    transfer_pred = transfer_model.predict(img_array)[0]

    cnn_result = {class_names[i]: float(cnn_pred[i]) for i in range(len(class_names))}
    transfer_result = {class_names[i]: float(transfer_pred[i]) for i in range(len(class_names))}

    return cnn_result, transfer_result

"""## Step 20: Launch the Gradio Interface
This creates a web UI with an image upload box and shows predictions from both models side by side.
"""

import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("## 🍎 Fruit Freshness Detector")
    gr.Markdown("Upload a fruit image to see predictions from both models.")

    with gr.Row():
        img_input = gr.Image(type="pil", label="Upload Image", height=250)

    with gr.Row():
        with gr.Column(scale=1):
            cnn_output = gr.Label(num_top_classes=3, label="Custom CNN")
        with gr.Column(scale=1):
            transfer_output = gr.Label(num_top_classes=3, label="Transfer Learning")

    btn = gr.Button("Predict")
    btn.click(fn=predict_fruit, inputs=img_input, outputs=[cnn_output, transfer_output])

demo.launch(debug=True)

"""## Step 21: Visualize Sample Predictions from Test Set
This picks a few random test images and shows the true label vs the model's predicted label with confidence — useful for the project report.
"""

import matplotlib.pyplot as plt
import numpy as np

test_images, test_labels = next(test_data)

# Sirf ek dafa predict karo, poore batch par
all_preds = transfer_model.predict(test_images)

plt.figure(figsize=(15, 10))

for i in range(9):
    plt.subplot(3, 3, i+1)
    img = test_images[i]
    true_label = class_names[np.argmax(test_labels[i])]

    pred = all_preds[i]
    pred_label = class_names[np.argmax(pred)]
    confidence = np.max(pred) * 100

    plt.imshow(img)
    color = 'green' if pred_label == true_label else 'red'
    plt.title(f"True: {true_label}\nPred: {pred_label} ({confidence:.1f}%)", color=color)
    plt.axis('off')

plt.tight_layout()
plt.show()